config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'static_pages/home'
  get 'static_pages/help'
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  root 'static_pages#home'
  resources :users
  resources :account_activations, only: [:edit]
  resources :microposts, only: [:create, :destroy]
  get '/microposts', to: 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png], message: "must be a valid image format" }, size: { less_than: 5.megabytes, message: "should be less than 5MB" }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy


  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # def User.digest(string)
  #   cost = ActiveModel::SecurePassword.min_cost ?
  #   BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
  #   BCrypt::Password.create(string, cost: cost)
  #  end
    
    
    
    # Returns a random token.

  # def User.new_token
  #   SecureRandom.urlsafe_base64
  # end

  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

   # Returns true if the given token matches the digest.
   def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?
    (remember_token)
  end
 
   # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def session_token
    remember_digest || remember
  end

  def feed
    Micropost.where(user_id: id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def hello
    render html: 'hello, world!'
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in, only: [:create, :destroy]
    before_action :correct_user, only: :destroy
    def create
        @micropost = current_user.microposts.build(micropost_params)
        @micropost.image.attach(params[:micropost][:image])

        if @micropost.save
            flash[:success] = "Micropost created!"
            redirect_to root_url
        else
            @feed_items = current_user.feed.paginate(page: params[:page])
            render 'static_pages/home', status: :unprocessable_entity
        end
    end

    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
    end

    private
    def micropost_params
        params.require(:micropost).permit(:content, :image)
    end
    def correct_user
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url, status: :see_other if @micropost.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email].downcase)
      # if user&.authenticate(params[:session][:password])
      if user && user.authenticate(params[:session][:password])
        forwarding_url = session[:forwarding_url]
        reset_session
        log_in user
        redirect_to forwarding_url || user
      else
        flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_url, status: :see_other
  end

  def new
  end
 
   
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
    @micropost = current_user.microposts.build
    @feed_items = current_user.feed.paginate(page: params[:page])
    end
    end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :admin_user, only: :destroy
  before_action :correct_user, only: [:edit, :update]
  def index
    @users = User.paginate(page: params[:page])
    end
   

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    end
   
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "OK!!!"
      redirect_to @user

    else
      render 'new', status: :unprocessable_entity
    end
   end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
    render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url, status: :see_other
  end
   


   private
  def user_params
    params.require(:user).permit(:name, :email, :password,
    :password_confirmation)
  end


  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url, status: :see_other
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url, status: :see_other) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url, status: :see_other) unless
   current_user.admin?
  end
   

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'CourseApp'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
        session[:session_token] = user.session_token
    end
       
    def current_user
        if (user_id = session[:user_id])
            user = User.find_by(id: user_id)
            if user && session[:session_token] == user.session_token
                @current_user = user
            end
            elsif (user_id = cookies.encrypted[:user_id])
                user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user           
            end
        end
    end

    def logged_in?
        !current_user.nil?
    end

# Forgets a persistent session.
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def log_out
        forget(current_user)
        reset_session
        @current_user = nil
    end
       
# Remembers a user in a persistent session.
    def remember(user)
        user.remember
        cookies.permanent.encrypted[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.encrypted[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end
    
    def current_user?(user)
        user && user == current_user
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#
       {gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
 <title><%= full_title(yield(:title)) %></title>
 <meta name="viewport" content="width=device-width, initialscale=1">
 <meta charset="utf-8">
 <%= csrf_meta_tags %>
 <%= csp_meta_tag %>
 <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>


 </head>
 <body>
 <header class="navbar navbar-fixed-top navbar-inverse">
 <div class="container">
 <%= link_to "Курсач", '#', id: "logo" %>
 <ul class="nav navbar-nav navbar-right">
 <li><%= link_to "Home", '/' %></li>
 <li><%= link_to "Users", users_path %></li>
<% if current_user %>
 <li><%= link_to "Profile", current_user %></li> 
 <li><%= link_to "Settings", edit_user_path(current_user) %></li>
 <li><%= link_to "Log out", logout_path, data: { "turbo-method": :delete } %></li>
 <% else %>
 <li><%= link_to "Log in", '/login' %></li>
 <% end %>
 </div>
</div>
<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %>
<% end %>

<% if logged_in? %>
 <div class="row">
 <aside class="col-md-4">
 <section class="user_info">
 <%= render 'shared/user_info' %>
 </section>
 <section class="micropost_form">
 <%= render 'shared/micropost_form' %>
 </section>
 </aside>
 </div>
<% else %>
 <h1>Welcome to the Sample App</h1>

<% end %>

    <%= yield %>


<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
        <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
        <span class="content"><%= micropost.content %></span>
        <%= image_tag micropost.image if micropost.image.attached? %>
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
        <%= link_to "delete", micropost, data: { "turbo-method": :delete, turbo_confirm: "You sure?" } %>
    <% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if @object && @object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@object.errors.count, "error") %>.
    </div>
    <ul>
      <% @object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
 <ol class="microposts">
 <%= render @feed_items %>
 </ol>
 <%= will_paginate @feed_items,
 params: { controller: :static_pages, action:
:home } %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost) do |f| %>
 <%= render 'shared/error_messages', object: f.object %>
 <div class="field">
 <%= f.text_area :content, placeholder: "Compose new micropost..." %>
 </div>
 <%= f.submit "Post", class: "btn btn-primary" %>
 <span class="image">
 <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
 </span>

<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost")
%></span>

app/views/static_pages/help.html.erb
 <% provide(:title, "Help") %>
 <title><%= yield(:title) %> | CDGcourseHelppage

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
 <head>
 <title><%= yield(:title) %> | CDGcourseHomepage
App</title>
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg
btn-primary" %>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |f| %>
    <%= render 'shared/error_messages', object: @user %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-
   control' %>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
   <% end %>

app/views/users/_user.html.erb
<li>
 <%= link_to user.name, user %>
 <% if current_user.admin? && !current_user?(user) %>
 | <%= link_to "delete", user, data: { "turbo-method": :delete, turbo_confirm: "You sure?" } %>
 <% end %>

</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
 <%= render 'form' %>
 <div class="gravatar_edit">
 <%= gravatar_for @user %>
 <a href="https://gravatar.com/emails" target="_blank">Change</a>
 </div>
 </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
<% render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
 <%= render 'form' %>
 </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
 <aside class="col-md-4">
 <section class="user_info">
 <h1>
 </h1>
 </section>
 </aside>
 <div class="col-md-8">
 <% if @user.microposts.any? %>
 <h3>Microposts (<%= @user.microposts.count %>)</h3>
 <ol class="microposts">
 <%= render @microposts %>
 </ol>
 <%= @microposts %>
 <% end %>
 </div>
</div>